# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SsProtocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InitResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInitResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InitResponse()
        x.Init(buf, n + offset)
        return x

    # InitResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InitResponse
    def Capabilities(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def InitResponseStart(builder): builder.StartObject(1)
def InitResponseAddCapabilities(builder, capabilities): builder.PrependUint64Slot(0, capabilities, 0)
def InitResponseEnd(builder): return builder.EndObject()
