# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SsProtocol

class MessageUnion(object):
    NONE = 0
    InitRequest = 1
    InitResponse = 2
    TerrainChunk = 3
    EnvironmentChunk = 4

